// Makes this workspace's first-party pieces visible to the reactor running from
// packages/workflow, without publishing them.
//
//   node demo-umh/scripts/install-pieces.mjs
//
// The reactor serves a piece from one of two places: a bundle fetched from a
// registry, or a "package piece" — one an installed reactor package declares in
// its `pieces` export and ships already built (subgraphs/workflow-runtime/
// piece-registry.ts). piece-paperless-ngx is not published,
// so the demo uses the second: each is built into packages/workflow/dist/pieces
// and declared in the manifest the registry reads there.
//
// Everything this writes is build output (packages/workflow/dist is gitignored)
// and `pnpm --filter workflow build` regenerates the manifest from
// packages/workflow/pieces/index.ts, dropping these entries. Re-run this after
// any build; it is idempotent.
//
// The tracked manifest is deliberately left alone: it declares what the
// workflow package *ships*, and a published copy of it must not claim pieces
// that only exist as sibling directories in this checkout.
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
);
const workflowRoot = path.join(repoRoot, "packages", "workflow");
const piecesDir = path.join(workflowRoot, "dist", "pieces");
const manifestFile = path.join(piecesDir, "index.mjs");

// Every UNPUBLISHED piece the demo's workflows use, by workspace directory.
// The bundle directory name is ours; the piece name comes from each package's
// own manifest, so the two cannot drift.
//
// The UMH piece is not here any more: umh-production-ledger ships it in its
// own pieces manifest, so the reactor finds it the moment that package is
// installed — no injection, and nothing for a rebuild to undo.
const PIECES = ["piece-paperless-ngx"];

if (!existsSync(manifestFile)) {
  // Without it the reactor piece — the document blocks every workflow here
  // writes through — would not be served either, and the workflows would fail
  // at their second step with nothing to say.
  console.error(
    `No built piece manifest at ${path.relative(repoRoot, manifestFile)}.\n` +
      "Run `pnpm --filter workflow build` first, then this script.",
  );
  process.exit(1);
}

const { pieces: existing } = await import(pathToFileURL(manifestFile).href);
const declared = new Map(existing.map((entry) => [entry.name, entry]));

for (const directory of PIECES) {
  const packageRoot = path.join(repoRoot, "packages", directory);
  const pkg = JSON.parse(
    await readFile(path.join(packageRoot, "package.json"), "utf8"),
  );
  // Named after the workspace directory rather than the scoped package name:
  // the bundle path ends up in the manifest, and a "@" in a directory name is
  // one more thing to quote in every shell that touches it.
  const bundle = path.posix.join("dist", "pieces", directory);
  execFileSync(
    process.execPath,
    [path.join(packageRoot, "scripts", "bundle.mjs"), "--out", path.join(workflowRoot, bundle)],
    { cwd: packageRoot, stdio: "inherit" },
  );
  declared.set(pkg.name, { name: pkg.name, version: pkg.version, bundle });
  console.log(`piece: ${pkg.name}@${pkg.version} -> ${bundle}`);
}

await mkdir(piecesDir, { recursive: true });
await writeFile(
  manifestFile,
  "// DEMO-LOCAL, regenerated by `pnpm --filter workflow build`.\n" +
    "// Written by demo-umh/scripts/install-pieces.mjs; re-run it after a build.\n" +
    `export const pieces = ${JSON.stringify([...declared.values()], null, 2)};\n` +
    "export default pieces;\n",
);
console.log(
  `\n${declared.size} package piece(s) declared in ${path.relative(repoRoot, manifestFile)}:`,
);
for (const entry of declared.values()) {
  console.log(`  ${entry.name}@${entry.version}`);
}
